// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/vless/server_config.proto

package vless

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Private typed extension points, never decoded from imported client JSON.
type ServerDispatcherConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerDispatcherConfig) Reset() {
	*x = ServerDispatcherConfig{}
	mi := &file_internal_vless_server_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerDispatcherConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerDispatcherConfig) ProtoMessage() {}

func (x *ServerDispatcherConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vless_server_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerDispatcherConfig.ProtoReflect.Descriptor instead.
func (*ServerDispatcherConfig) Descriptor() ([]byte, []int) {
	return file_internal_vless_server_config_proto_rawDescGZIP(), []int{0}
}

type ServerInboundConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VlessConfig   []byte                 `protobuf:"bytes,1,opt,name=vless_config,json=vlessConfig,proto3" json:"vless_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInboundConfig) Reset() {
	*x = ServerInboundConfig{}
	mi := &file_internal_vless_server_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInboundConfig) ProtoMessage() {}

func (x *ServerInboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vless_server_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInboundConfig.ProtoReflect.Descriptor instead.
func (*ServerInboundConfig) Descriptor() ([]byte, []int) {
	return file_internal_vless_server_config_proto_rawDescGZIP(), []int{1}
}

func (x *ServerInboundConfig) GetVlessConfig() []byte {
	if x != nil {
		return x.VlessConfig
	}
	return nil
}

var File_internal_vless_server_config_proto protoreflect.FileDescriptor

const file_internal_vless_server_config_proto_rawDesc = "" +
	"\n" +
	"\"internal/vless/server_config.proto\x12\rquiclab.vless\"\x18\n" +
	"\x16ServerDispatcherConfig\"8\n" +
	"\x13ServerInboundConfig\x12!\n" +
	"\fvless_config\x18\x01 \x01(\fR\vvlessConfigB\x18Z\x16quiclab/internal/vlessb\x06proto3"

var (
	file_internal_vless_server_config_proto_rawDescOnce sync.Once
	file_internal_vless_server_config_proto_rawDescData []byte
)

func file_internal_vless_server_config_proto_rawDescGZIP() []byte {
	file_internal_vless_server_config_proto_rawDescOnce.Do(func() {
		file_internal_vless_server_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_vless_server_config_proto_rawDesc), len(file_internal_vless_server_config_proto_rawDesc)))
	})
	return file_internal_vless_server_config_proto_rawDescData
}

var file_internal_vless_server_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_vless_server_config_proto_goTypes = []any{
	(*ServerDispatcherConfig)(nil), // 0: quiclab.vless.ServerDispatcherConfig
	(*ServerInboundConfig)(nil),    // 1: quiclab.vless.ServerInboundConfig
}
var file_internal_vless_server_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_vless_server_config_proto_init() }
func file_internal_vless_server_config_proto_init() {
	if File_internal_vless_server_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_vless_server_config_proto_rawDesc), len(file_internal_vless_server_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_vless_server_config_proto_goTypes,
		DependencyIndexes: file_internal_vless_server_config_proto_depIdxs,
		MessageInfos:      file_internal_vless_server_config_proto_msgTypes,
	}.Build()
	File_internal_vless_server_config_proto = out.File
	file_internal_vless_server_config_proto_goTypes = nil
	file_internal_vless_server_config_proto_depIdxs = nil
}
