(()=>{'use strict';
const $=s=>document.querySelector(s),root=$('#mdm-editor'),base=root.dataset.base,id=root.dataset.id,csrf=root.dataset.csrf;
const el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
let state,doc,original,revision=0,generation=0,dirty=false,busy=false,mode='current',applyRequest=null;
const commandRequests={};
const copy=x=>JSON.parse(JSON.stringify(x)),message=(s,error=false)=>{$('#message').textContent=s;$('#message').className=error?'error':'';};
const uuid=()=>crypto.randomUUID();
const can=right=>state?.binding.active && state.binding.grantedRights[right] && state.report?.capabilities?.includes('web-control-v1');
function changed(){dirty=true;applyRequest=null;$('#draft-note').textContent='Есть несохранённые изменения. Для отправки нажмите «Применить».';}
async function post(path,fields){const r=await fetch(base+path,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({csrf,id,...fields})});if(!r.ok)throw Error(r.status===409?'Конфликт или MDM приостановлено. Перечитайте состояние перед повтором.':r.status===403?'Нет разрешения на эту операцию.':'Сервер отклонил запрос ('+r.status+').');return r.json();}
function field(host,title,value,set,type='text',choices){const label=el('label',title),input=el(choices?'select':'input');if(choices){for(const [v,t]of choices){const o=el('option',t);o.value=v;input.append(o);}input.value=value;}else{input.type=type;if(type==='checkbox')input.checked=!!value;else input.value=value??'';}input.onchange=()=>{set(type==='checkbox'?input.checked:type==='number'?Number(input.value):input.value);changed();};label.append(input);host.append(label);return input;}
function renderConfig(){const host=$('#configuration');host.replaceChildren();if(!doc){host.append(el('p','Для редактирования нужен свежий отчёт телефона и разрешение на управление настройками.'));return;}
field(host,'Режим конфигурации',mode,v=>mode=v,'text',[['current','Текущая — сохранить изменения после отключения MDM'],['external','Внешняя — вернуть личные настройки после отключения MDM']]);
const grid=el('div');grid.className='grid';host.append(grid);const profiles=doc.profiles.map(p=>[p.id,p.name]);
field(grid,'Основное подключение',doc.currentProfileId,v=>doc.currentProfileId=v,'text',profiles);
field(grid,'Несколько выходов',doc.multiple,v=>doc.multiple=v,'checkbox');
field(grid,'DNS',doc.dns.mode,v=>doc.dns.mode=v,'text',[['system','Системный'],['tunnel','Через туннель']]);
field(grid,'Выход для DNS',doc.dns.profileId,v=>doc.dns.profileId=v,'text',profiles);
field(grid,'Общий лимит LTE, МиБ (0 — без лимита)',doc.budget.limitBytes/1048576,v=>doc.budget.limitBytes=Math.round(v*1048576),'number');
field(grid,'Диагностические журналы',doc.diagnostics.enabled,v=>doc.diagnostics.enabled=v,'checkbox');
field(grid,'Подробные журналы',doc.diagnostics.detailed,v=>doc.diagnostics.detailed=v,'checkbox');
if(doc.reserve){const reserve=el('fieldset');reserve.append(el('legend','Резервные сети'));host.append(reserve);for(const[k,label]of Object.entries({wifi_on:'Wi-Fi при включённом экране',wifi_off:'Wi-Fi при выключенном экране',cell_on:'LTE при включённом экране',cell_off:'LTE при выключенном экране',metered_wifi:'Разрешить проверки лимитного Wi-Fi'}))field(reserve,label,doc.reserve[k],v=>doc.reserve[k]=v,'checkbox');}
for(const p of doc.profiles){const box=el('div');box.className='profile';host.append(box);field(box,'Название подключения',p.name,v=>{p.name=v;});const s=p.settings;
field(box,'Включено в набор выходов',doc.enabledProfileIds.includes(p.id),v=>{doc.enabledProfileIds=doc.enabledProfileIds.filter(x=>x!==p.id);if(v)doc.enabledProfileIds.push(p.id);},'checkbox');
field(box,'Транспорт',s.transport||'quic',v=>s.transport=v,'text',[['quic','QUIC'],['https','HTTPS'],['awg','AmneziaWG'],['vless','VLESS']]);
for(const[k,label]of Object.entries({endpoint:'Адрес:порт',hostname:'Имя узла',quic_endpoint:'QUIC адрес:порт',https_endpoint:'HTTPS адрес:порт',awg_endpoint:'AWG адрес:порт',vless_endpoint:'VLESS адрес:порт',server_name:'SNI',verify_name:'Имя проверки сертификата',dns:'DNS IPv4',routes:'IPv4-маршруты (CIDR через запятую)',transit_endpoint:'Мультиплексор:порт'}))field(box,label,s[k]||'',v=>s[k]=v);
field(box,'Маршрутизация',s.mode??0,v=>s.mode=Number(v),'text',[['0','Весь трафик'],['1','Выбранные приложения'],['2','Кроме выбранных приложений'],['3','Подсети IPv4']]);
field(box,'Использовать общий список приложений',s.global_apps??false,v=>{s.global_apps=v;appList();},'checkbox');
field(box,'Максимальная доступность',s.max_availability||false,v=>s.max_availability=v,'checkbox');
field(box,'Мультиплексирование',s.demux_enabled||false,v=>s.demux_enabled=v,'checkbox');
for(const transport of ['quic','https']){field(box,transport.toUpperCase()+' — режим',s[transport+'_mode']||'auto',v=>s[transport+'_mode']=v,'text',[['auto','Автоматически'],['reserve','Только резерв'],['disabled','Не использовать']]);field(box,transport.toUpperCase()+' — размер пула',s[transport+'_pool_size']||1,v=>s[transport+'_pool_size']=v,'number');field(box,transport.toUpperCase()+' — проверять резерв',s[transport+'_check_reserve']||false,v=>s[transport+'_check_reserve']=v,'checkbox');}
const keys=el('details');keys.append(el('summary','Заменить данные доступа'));keys.append(el('p','Пустые поля сохраняют существующие ключи. Вставьте новые данные только для явной замены.'));box.append(keys);
for(const[k,label]of Object.entries({vless_uri:'VLESS ссылка',awg_config:'AWG конфигурация',certificate:'Клиентский сертификат PEM',key:'Закрытый ключ PEM'})){const l=el('label',label),t=el('textarea');t.autocomplete='off';t.value=p.identity?.[k]||'';t.onchange=()=>{p.identity=p.identity||{};if(t.value.trim())p.identity[k]=t.value.trim();else delete p.identity[k];if(!Object.keys(p.identity).length)delete p.identity;changed();};l.append(t);keys.append(l);}
const remove=el('button','Удалить подключение');remove.className='danger';remove.onclick=()=>{if(doc.profiles.length===1){message('Нужно сохранить хотя бы одно подключение.',true);return;}if(!confirm('Удалить подключение '+p.name+'?'))return;doc.profiles=doc.profiles.filter(x=>x.id!==p.id);doc.enabledProfileIds=doc.enabledProfileIds.filter(x=>x!==p.id);if(doc.currentProfileId===p.id)doc.currentProfileId=doc.profiles[0].id;if(doc.dns.profileId===p.id)doc.dns.profileId=doc.currentProfileId;changed();renderConfig();renderApps();};box.append(remove);
}
const add=el('button','Добавить подключение');add.onclick=()=>{if(doc.profiles.length>=32){message('Максимум 32 подключения.',true);return;}doc.profiles.push({id:uuid(),name:'Новое подключение',settings:{transport:'quic',mode:0}});changed();renderConfig();renderApps();};host.append(add);
}
function renderApps(){const select=$('#apps-profile'),previous=select.value;select.replaceChildren();for(const [value,text]of [['global','Общий список'],...(doc?.profiles||[]).map(p=>[p.id,p.name])]){const o=el('option',text);o.value=value;select.append(o);}if([...select.options].some(x=>x.value===previous))select.value=previous;appList();}
function appList(){const host=$('#app-list');host.replaceChildren();if(!doc)return;const inv=state.report?.inventory;const target=appsTarget();$('#inventory-note').textContent=(target.global?'Общий список — изменения действуют на все использующие его подключения.':'Индивидуальный список подключения.')+' Выбрано: '+selectApps().length+'. '+(inv?.complete?'Получен полный список.':'Список ограничен видимостью Android. Отсутствующие выбранные пакеты сохранены.');
const selected=()=>selectApps(),items=new Map((inv?.entries||[]).map(a=>[a.packageId,a.label]));for(const pkg of selected())if(!items.has(pkg))items.set(pkg,'Не найдено на телефоне');
const query=$('#app-search').value.toLowerCase();for(const[pkg,label]of [...items].sort((a,b)=>Number(selected().includes(b[0]))-Number(selected().includes(a[0]))||a[1].localeCompare(b[1]))){if(!(label+' '+pkg).toLowerCase().includes(query))continue;field(host,label+' · '+pkg,selected().includes(pkg),on=>{const next=selected().filter(x=>x!==pkg);if(on)next.push(pkg);const target=appsTarget();if(target.global)doc.globalApps=next;else target.profile.settings.apps=next;appList();},'checkbox');}}
function appsTarget(){const id=$('#apps-profile').value,profile=doc.profiles.find(p=>p.id===id);return {profile,global:id==='global'||profile?.settings.global_apps===true};}
function selectApps(){const target=appsTarget();return target.global?(doc.globalApps||[]):(target.profile?.settings.apps||[]);}
function preview(){if(!doc)return;const lines=[];function walk(a,b,path){if(path.endsWith('.identity')){if(b)lines.push(path+': данные доступа будут заменены');return;}if(JSON.stringify(a)===JSON.stringify(b))return;if(a&&b&&typeof a==='object'&&typeof b==='object'){for(const k of new Set([...Object.keys(a),...Object.keys(b)]))walk(a[k],b[k],path+'.'+k);}else lines.push(path+': '+JSON.stringify(a)+' → '+JSON.stringify(b));}walk(original,doc,'Конфигурация');$('#diff').textContent=lines.join('\n')||'Параметры не изменены.';}
function status(){const b=state.binding,r=state.report;$('#title').textContent=r?.name||'Управление устройством';const desired=state.desired?.revision||0,applied=r?.appliedRevision||0;const errors=(state.events||[]).filter(e=>e.kind==='config_result'&&e.revision===desired&&e.result!=='applied');
$('#status').replaceChildren(el('p',b.active?'MDM включено':'MDM приостановлено'),el('p','Версия: '+(r?.appVersion||'нет отчёта')),el('p','Последняя связь: '+(state.receivedAt&& !state.receivedAt.startsWith('0001')?new Date(state.receivedAt).toLocaleString():'нет данных')),el('p','VPN: '+({running:'служба запущена',stopped:'выключен',starting:'запускается',error:'ошибка'}[r?.vpnState]||'нет разрешения или данных')),el('p',desired?(applied>=desired?'Применено: ревизия '+applied:errors.length?'Ошибка применения: '+errors.at(-1).result:'Ожидает применения: ревизия '+desired):'Удалённые изменения ещё не отправлялись'));
const vpnError=(state.events||[]).filter(e=>e.kind==='config_vpn_result'&&e.revision===desired).at(-1);if(vpnError&&vpnError.result!=='running')$('#status').append(el('p','Конфигурация сохранена; VPN не запустился: '+vpnError.result));
const rights=Object.entries(b.grantedRights||{}).filter(([k,v])=>v===true).map(([k])=>({config:'настройки',vpn:'VPN',telemetry:'телеметрия',geo:'Wi-Fi/соты',coordinates:'координаты'}[k]||k));$('#status').append(el('p','Разрешено: '+(rights.join(', ')||'нет прав')));
const requests=(state.events||[]).filter(e=>e.actor==='admin'&&['vpn_start','vpn_stop'].includes(e.kind)).slice(-5);for(const request of requests){const result=(state.events||[]).filter(e=>e.kind==='command_result'&&e.commandId===request.commandId).at(-1);const pending=(state.commands||[]).find(c=>c.id===request.commandId);const label=result?.result||(pending&&new Date(pending.expiresAt)>new Date()?'ожидает выполнения':'срок истёк или команда отменена');$('#status').append(el('p',(request.kind==='vpn_start'?'Включение VPN: ':'Выключение VPN: ')+({starting:'запускается',running:'служба запущена',stopped:'выключен',needs_android_consent:'нужно разрешение Android на телефоне',vpn_start_failed:'ошибка запуска',permission_denied:'нет разрешения',expired:'срок истёк',interrupted:'выполнение прервано'}[label]||label)));}
$('#start').disabled=busy||!can('vpn');$('#stop').disabled=busy||!can('vpn');$('#apply').disabled=busy||!can('config')||!doc;$('#preview').disabled=!doc;
const events=$('#event-list');events.replaceChildren();const table=el('table');for(const e of [...(state.events||[])].reverse()){const tr=el('tr');for(const text of [new Date(e.occurredAt).toLocaleString(),e.actor,e.kind,e.result||'',e.revision?'r'+e.revision:''])tr.append(el('td',text));table.append(tr);}events.append(table);
}
async function load(reset=false){try{const r=await fetch(base+'mdm/state?id='+encodeURIComponent(id),{cache:'no-store'});if(!r.ok)throw Error('Не удалось получить состояние ('+r.status+').');state=await r.json();if(reset||!doc){const source=state.desired?.document||state.report?.configuration;doc=source?copy(source):null;original=doc?copy(doc):null;mode=state.desired?.mode||'current';revision=state.desired?.revision||0;generation=state.report?.configGeneration||0;dirty=false;applyRequest=null;renderConfig();renderApps();}status();if(reset)message(state.report?.capabilities?.includes('web-control-v1')?'Состояние обновлено.':'Для WEB-управления обновите приложение и разрешите управление настройками/VPN.');}catch(e){message(e.message,true);}}
$('#apps-profile').onchange=appList;$('#app-search').oninput=appList;$('#preview').onclick=preview;$('#reload').onclick=()=>{if(!dirty||confirm('Отбросить несохранённые изменения?'))load(true);};
$('#apply').onclick=async()=>{if(busy||!can('config'))return;preview();if(!confirm('Применить настройки к телефону? VPN может кратковременно переподключиться.'))return;busy=true;status();try{applyRequest=applyRequest||uuid();const out=await post('mdm/config',{expectedRevision:revision,expectedGeneration:generation,requestID:applyRequest,mode,document:JSON.stringify(doc)});revision=out.revision;original=copy(doc);dirty=false;applyRequest=null;$('#draft-note').textContent='Изменения отправлены. Подтверждение телефона показано в обзоре.';$('#diff').textContent='';message('Отправлено: ревизия '+revision+'. Ожидаем подтверждение телефона.');}catch(e){message(e.message,true);}finally{busy=false;status();}};
for(const[kind,button]of [['vpn_start','#start'],['vpn_stop','#stop']])$(button).onclick=async()=>{if(busy)return;busy=true;status();try{const out=await post('mdm/command',{kind,requestID:commandRequests[kind]||(commandRequests[kind]=uuid())});delete commandRequests[kind];message('Команда отправлена. Действует до '+new Date(out.expiresAt).toLocaleTimeString());}catch(e){message(e.message,true);}finally{busy=false;status();}};
for(const button of document.querySelectorAll('[data-tab]'))button.onclick=()=>{for(const b of document.querySelectorAll('[data-tab]')){const active=b===button;b.setAttribute('aria-selected',String(active));$('#'+b.dataset.tab).hidden=!active;}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});load(true);setInterval(()=>{if(!busy)load(false);},10000);
})();
