
(()=>{const form=document.querySelector('#settings');if(!form)return;const field=n=>form.elements.namedItem(n),feedback=document.querySelector('#feedback');let dirty=false;form.addEventListener('input',()=>dirty=true);form.addEventListener('change',()=>dirty=true);addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
for(const tab of document.querySelectorAll('[data-tab]'))tab.addEventListener('click',()=>{for(const t of document.querySelectorAll('[data-tab]'))t.setAttribute('aria-selected',String(t===tab));for(const panel of document.querySelectorAll('.panel'))panel.hidden=panel.id!==tab.dataset.tab});
function security(){for(const el of document.querySelectorAll('[data-security]'))el.hidden=el.dataset.security!==field('security').value}field('security').addEventListener('change',security);security();
function mode(){document.querySelector('#demux-field').hidden=field('mode').value!=='demux-only'}field('mode').addEventListener('change',mode);mode();
function ids(){const select=field('reality_export_short_id'),value=select.value||select.dataset.selected||'';select.replaceChildren(new Option('Первый из списка',''));for(const id of [...new Set(field('reality_ids').value.split(',').map(x=>x.trim()).filter(Boolean))])select.add(new Option(id,id));if([...select.options].some(x=>x.value===value))select.value=value;select.dataset.selected=''}field('reality_ids').addEventListener('input',ids);ids();
field('reality_private_key').addEventListener('input',()=>{document.querySelector('#public-key').value='';field('confirm_key_change').checked=false});
document.querySelector('#copy-key').onclick=async()=>{const el=document.querySelector('#public-key');try{await navigator.clipboard.writeText(el.value)}catch{el.focus();el.select()}};
for(const button of document.querySelectorAll('[data-tool]'))button.onclick=async()=>{button.disabled=true;feedback.textContent='';try{const data=new URLSearchParams({csrf:field('csrf').value,target:field('reality_target').value,server_name:field('server_name').value});const r=await fetch(form.dataset.base+'vless/'+button.dataset.tool,{method:'POST',body:data});if(!r.ok)throw new Error(await r.text());const out=await r.json();if(out.private_key){field('reality_private_key').value=out.private_key;document.querySelector('#public-key').value=out.public_key;field('confirm_key_change').checked=false;dirty=true}if(out.short_id){const el=field('reality_ids');el.value+=(el.value.trim()?', ':'')+out.short_id;ids();dirty=true}if(out.message)document.querySelector('#target-result').textContent=out.message}catch(e){feedback.textContent=e.message}finally{button.disabled=false}};
form.onsubmit=async e=>{e.preventDefault();if(field('reality_private_key').value&&field('security').value==='reality'&&!field('confirm_key_change').checked){feedback.textContent='Подтвердите замену ключа.';return}const button=form.querySelector('[type=submit]');button.disabled=true;feedback.textContent='Проверяем и применяем…';try{const data=new URLSearchParams(new FormData(form));if(field('mode').value==='standalone')data.set('demux_endpoint','');const r=await fetch(form.action,{method:'POST',body:data});if(!r.ok)throw new Error(await r.text());if(!r.url.endsWith('/vless'))throw new Error('Сессия администратора истекла. Войдите снова; черновик оставлен в форме.');dirty=false;location.reload()}catch(e){feedback.textContent=e.message}finally{button.disabled=false}};
})();
