package ru.vpnc.quiclab
import android.graphics.BitmapFactory
import androidx.test.platform.app.InstrumentationRegistry
import com.google.zxing.*
import com.google.zxing.common.HybridBinarizer
import com.google.zxing.qrcode.QRCodeWriter
import java.io.File
import org.json.JSONObject
import org.junit.Assert.*
import org.junit.Test

class ProfileImportTest {
    @Test fun echoQRDecodesAndValidatesWithoutIdentity() {
        val raw=JSONObject().put("version",1).put("kind","echo").put("endpoint","lab.example:4433").put("hostname","lab.example").toString()
        val bits=QRCodeWriter().encode(raw,BarcodeFormat.QR_CODE,400,400)
        val pixels=IntArray(400*400){i->if(bits.get(i%400,i/400))0xff000000.toInt() else 0xffffffff.toInt()}
        val decoded=MultiFormatReader().decode(BinaryBitmap(HybridBinarizer(RGBLuminanceSource(400,400,pixels)))).text
        assertEquals("echo",ProfileImport.validate(JSONObject(decoded)))
        val invalid=JSONObject(raw).put("key","secret")
        try{ProfileImport.validate(invalid);fail("echo accepted key")}catch(_:IllegalArgumentException){}
    }
    @Test fun enrollmentRejectsCleartextAndRedirectLikePayloads() {
        for(raw in listOf("http://lab.example/enroll#"+"a".repeat(48),"https://user@lab.example/enroll#"+"a".repeat(48),"https://lab.example/enroll?token=x#"+"a".repeat(48))) {
            try{ProfileImport.enrollment(raw);fail(raw)}catch(_:IllegalArgumentException){}
        }
    }
    // Opt-in integration: PNG is generated by the real admin and pushed to app external files.
    @Test fun importServerQRWhenProvided() {
        val inst=InstrumentationRegistry.getInstrumentation()
        val name=InstrumentationRegistry.getArguments().getString("qr_file") ?: return
        require(!name.contains('/') && !name.contains('\\'))
        val file=File(inst.targetContext.getExternalFilesDir(null),name)
        val bmp=BitmapFactory.decodeFile(file.absolutePath) ?: error("QR PNG missing")
        val pixels=IntArray(bmp.width*bmp.height);bmp.getPixels(pixels,0,bmp.width,0,0,bmp.width,bmp.height)
        val decoded=MultiFormatReader().decode(BinaryBitmap(HybridBinarizer(RGBLuminanceSource(bmp.width,bmp.height,pixels)))).text
        val profile=ProfileImport.fetch(decoded)
        assertEquals("vpn",ProfileImport.save(inst.targetContext,profile))
        assertTrue(VpnIdentity.load(inst.targetContext).getString("key").contains("PRIVATE KEY"))
        try {ProfileImport.fetch(decoded);fail("QR reused")}catch(_:IllegalArgumentException){}
    }
}
